before:
  hooks:
    - go mod download
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0 # 禁用 CGO，强制静态链接
    goos:
      - freebsd
      - linux
      - windows
      - darwin
      - openbsd
    goarch:
      - amd64
      - arm
      - arm64
      - 386
    goarm:
      - 7
    gomips:
      - hardfloat
      - softfloat
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{ .CommitDate }}
archives:
  - name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ if eq .Os "openbsd" }}OpenBSD{{ else }}{{ title .Os }}{{ end }}_{{ if eq .Arch "386" }}i386{{ else if eq .Arch "amd64" }}x86_64{{ else if eq .Arch "arm" }}armv7{{ else if eq .Arch "arm64" }}arm64{{ else if eq .Arch "riscv64" }}riscv64{{ else }}{{ .Arch }}{{ end }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'